name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push request event for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    # Our previously created self-hosted runner
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: ["7.0.x"]

    # A sequence of tasks that will execute as part of the job
    steps:
      # Checks out repository so our job can access it
      - uses: actions/checkout@v3

      # Stop the production service during deployment.
      - name: Stop Service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: ./stop-service.sh ${{ secrets.SERVICENAME }}

      # Setup the .NET enviroment
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      # We will output publish files to the folder we previously created
      - name: Publish
        run: dotnet publish  -c Release --no-restore --no-build --output /var/www/contact

      - name: Publish Deployment
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: /var/www/contact
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Start Service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: ./start-service.sh ${{ secrets.SERVICENAME }}
